apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-nginx
  name: front-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: front-nginx